#pragma once


//COPIED AND PASTED FROM "glfw3.h" file to localize the mouse button code defines.
#define ONURALP_MOUSE_BUTTON_1         0
#define ONURALP_MOUSE_BUTTON_2         1
#define ONURALP_MOUSE_BUTTON_3         2
#define ONURALP_MOUSE_BUTTON_4         3
#define ONURALP_MOUSE_BUTTON_5         4
#define ONURALP_MOUSE_BUTTON_6         5
#define ONURALP_MOUSE_BUTTON_7         6
#define ONURALP_MOUSE_BUTTON_8         7
#define ONURALP_MOUSE_BUTTON_LAST      ONURALP_MOUSE_BUTTON_8
#define ONURALP_MOUSE_BUTTON_LEFT      ONURALP_MOUSE_BUTTON_1
#define ONURALP_MOUSE_BUTTON_RIGHT     ONURALP_MOUSE_BUTTON_2
#define ONURALP_MOUSE_BUTTON_MIDDLE    ONURALP_MOUSE_BUTTON_3
